MATCH (ne:Personality {name: 'Neuroticism'})

MERGE (attr1:Personality:L1 {name: 'Anxiety', description: 'Feeling of worry, nervousness, or unease about something with an uncertain outcome.'})-[:IS_TRAIT]-(ne)
MERGE (attr2:Personality:L1 {name: 'Moodiness', description: 'Frequent changes in mood; tendency to experience feelings that are easily changed.'})-[:IS_TRAIT]-(ne)
MERGE (attr3:Personality:L1 {name: 'Vulnerability to Stress', description: 'Susceptibility to being easily stressed or overwhelmed by challenging situations.'})-[:IS_TRAIT]-(ne)
MERGE (attr4:Personality:L1 {name: 'Emotional Instability', description: 'Tendency to have unpredictable and rapid changes in emotions.'})-[:IS_TRAIT]-(ne)
MERGE (attr5:Personality:L1 {name: 'Anger', description: 'Feeling or showing strong annoyance, displeasure, or hostility; frustration.'})-[:IS_TRAIT]-(ne)
MERGE (attr6:Personality:L1 {name: 'Self-Consciousness', description: 'Acute awareness of oneself, leading to feelings of shyness or embarrassment.'})-[:IS_TRAIT]-(ne)
MERGE (attr7:Personality:L1 {name: 'Immoderation', description: 'Lack of restraint in controlling one\'s desires or feelings.'})-[:IS_TRAIT]-(ne)
MERGE (attr8:Personality:L1 {name: 'Depression', description: 'Feeling of severe despondency and dejection.'})-[:IS_TRAIT]-(ne)